spring:
  cloud:
    gcp:
      project-id: comeat2024
      sql:
        enabled: true
        database-name: jeogongtongDB
        instance-connection-name: comeat2024:asia-northeast3:jeogongtong
      storage:
        credentials:
          location: file:/comeat2024-212280a1b64c.json
          scopes: https://www.googleapis.com/auth/pubsub,https://www.googleapis.com/auth/sqlservice.admin


  datasource:
    url: jdbc:mysql://34.47.89.182:3306/jeogongtongDB?useSSL=false&serverTimezone=UTC
    username: comeat
    password: tkqwlf0000
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#    show-sql: true
#  h2:
#    console:
#      enabled: true
#  jpa:
#    properties:
#      hibernate:
#        ddl-auto: update
#        dialect: org.hibernate.dialect.H2Dialect
#
#

#
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: f7a9fc97c6ad206d16f1452ec5174805
#            client-secret: YWxsNR9PN1Cd8Rsv3u5of2ja62GC1OxF
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
